2024-12-06 16:45:41,723 INFO    MainThread:1603956 [wandb_setup.py:_flush():68] Current SDK version is 0.19.0
2024-12-06 16:45:41,723 INFO    MainThread:1603956 [wandb_setup.py:_flush():68] Configure stats pid to 1603956
2024-12-06 16:45:41,723 INFO    MainThread:1603956 [wandb_setup.py:_flush():68] Loading settings from /data/students/mary/.config/wandb/settings
2024-12-06 16:45:41,723 INFO    MainThread:1603956 [wandb_setup.py:_flush():68] Loading settings from /raid/students/mary/mlops-exercises/ME6/model_dev/wandb/settings
2024-12-06 16:45:41,723 INFO    MainThread:1603956 [wandb_setup.py:_flush():68] Loading settings from environment variables
2024-12-06 16:45:41,723 INFO    MainThread:1603956 [wandb_init.py:_log_setup():528] Logging user logs to /raid/students/mary/mlops-exercises/ME6/model_dev/wandb/run-20241206_164541-94217qrn/logs/debug.log
2024-12-06 16:45:41,723 INFO    MainThread:1603956 [wandb_init.py:_log_setup():529] Logging internal logs to /raid/students/mary/mlops-exercises/ME6/model_dev/wandb/run-20241206_164541-94217qrn/logs/debug-internal.log
2024-12-06 16:45:41,723 INFO    MainThread:1603956 [wandb_init.py:init():639] calling init triggers
2024-12-06 16:45:41,723 INFO    MainThread:1603956 [wandb_init.py:init():645] wandb.init called with sweep_config: {}
config: {}
2024-12-06 16:45:41,724 INFO    MainThread:1603956 [wandb_init.py:init():688] starting backend
2024-12-06 16:45:41,724 INFO    MainThread:1603956 [wandb_init.py:init():692] sending inform_init request
2024-12-06 16:45:41,726 INFO    MainThread:1603956 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-12-06 16:45:41,727 INFO    MainThread:1603956 [wandb_init.py:init():705] backend started and connected
2024-12-06 16:45:41,728 INFO    MainThread:1603956 [wandb_run.py:_label_probe_notebook():1327] probe notebook
2024-12-06 16:45:41,728 INFO    MainThread:1603956 [wandb_run.py:_label_probe_notebook():1337] Unable to probe notebook: Expecting value: line 1 column 1 (char 0)
2024-12-06 16:45:41,728 INFO    MainThread:1603956 [wandb_init.py:init():798] updated telemetry
2024-12-06 16:45:41,728 INFO    MainThread:1603956 [wandb_init.py:init():830] communicating run to backend with 90.0 second timeout
2024-12-06 16:46:08,188 WARNING MainThread:1603956 [wandb_init.py:init():1309] interrupted
Traceback (most recent call last):
  File "/data/students/mary/anaconda3/envs/AI231_ME6/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1305, in init
    return wi.init()
           ^^^^^^^^^
  File "/data/students/mary/anaconda3/envs/AI231_ME6/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 833, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/data/students/mary/anaconda3/envs/AI231_ME6/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 279, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/students/mary/anaconda3/envs/AI231_ME6/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/students/mary/anaconda3/envs/AI231_ME6/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 122, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/students/mary/anaconda3/envs/AI231_ME6/lib/python3.11/threading.py", line 629, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/students/mary/anaconda3/envs/AI231_ME6/lib/python3.11/threading.py", line 331, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2024-12-06 16:58:52,084 INFO    MainThread:1603956 [wandb_setup.py:_flush():68] Current SDK version is 0.19.0
2024-12-06 16:58:52,084 INFO    MainThread:1603956 [wandb_setup.py:_flush():68] Configure stats pid to 1603956
2024-12-06 16:58:52,084 INFO    MainThread:1603956 [wandb_setup.py:_flush():68] Loading settings from /data/students/mary/.config/wandb/settings
2024-12-06 16:58:52,085 INFO    MainThread:1603956 [wandb_setup.py:_flush():68] Loading settings from /raid/students/mary/mlops-exercises/ME6/model_dev/wandb/settings
2024-12-06 16:58:52,085 INFO    MainThread:1603956 [wandb_setup.py:_flush():68] Loading settings from environment variables
2024-12-06 16:58:52,085 INFO    MainThread:1603956 [wandb_init.py:_log_setup():528] Logging user logs to /raid/students/mary/mlops-exercises/ME6/model_dev/wandb/run-20241206_165852-364857ag/logs/debug.log
2024-12-06 16:58:52,085 INFO    MainThread:1603956 [wandb_init.py:_log_setup():529] Logging internal logs to /raid/students/mary/mlops-exercises/ME6/model_dev/wandb/run-20241206_165852-364857ag/logs/debug-internal.log
2024-12-06 16:58:52,085 INFO    MainThread:1603956 [wandb_init.py:init():639] calling init triggers
2024-12-06 16:58:52,085 INFO    MainThread:1603956 [wandb_init.py:init():645] wandb.init called with sweep_config: {}
config: {}
2024-12-06 16:58:52,085 INFO    MainThread:1603956 [wandb_init.py:init():688] starting backend
2024-12-06 16:58:52,085 INFO    MainThread:1603956 [wandb_init.py:init():692] sending inform_init request
2024-12-06 16:58:52,086 INFO    MainThread:1603956 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-12-06 16:58:52,086 INFO    MainThread:1603956 [wandb_init.py:init():705] backend started and connected
2024-12-06 16:58:52,088 INFO    MainThread:1603956 [wandb_run.py:_label_probe_notebook():1327] probe notebook
2024-12-06 16:58:52,088 INFO    MainThread:1603956 [wandb_run.py:_label_probe_notebook():1337] Unable to probe notebook: Expecting value: line 1 column 1 (char 0)
2024-12-06 16:58:52,088 INFO    MainThread:1603956 [wandb_init.py:init():798] updated telemetry
2024-12-06 16:58:52,088 INFO    MainThread:1603956 [wandb_init.py:init():830] communicating run to backend with 90.0 second timeout
2024-12-06 17:00:22,106 ERROR   MainThread:1603956 [wandb_init.py:init():857] encountered error: Run initialization has timed out after 90.0 sec. Please try increasing the timeout with the `init_timeout` setting: `wandb.init(settings=wandb.Settings(init_timeout=120))`.
2024-12-06 17:00:22,107 ERROR   MainThread:1603956 [wandb_init.py:init():1315] error in wandb.init()
Traceback (most recent call last):
  File "/data/students/mary/anaconda3/envs/AI231_ME6/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1305, in init
    return wi.init()
           ^^^^^^^^^
  File "/data/students/mary/anaconda3/envs/AI231_ME6/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 863, in init
    raise error
wandb.errors.errors.CommError: Run initialization has timed out after 90.0 sec. Please try increasing the timeout with the `init_timeout` setting: `wandb.init(settings=wandb.Settings(init_timeout=120))`.
2024-12-06 17:03:15,651 INFO    MainThread:1603956 [wandb_setup.py:_flush():68] Current SDK version is 0.19.0
2024-12-06 17:03:15,652 INFO    MainThread:1603956 [wandb_setup.py:_flush():68] Configure stats pid to 1603956
2024-12-06 17:03:15,652 INFO    MainThread:1603956 [wandb_setup.py:_flush():68] Loading settings from /data/students/mary/.config/wandb/settings
2024-12-06 17:03:15,652 INFO    MainThread:1603956 [wandb_setup.py:_flush():68] Loading settings from /raid/students/mary/mlops-exercises/ME6/model_dev/wandb/settings
2024-12-06 17:03:15,652 INFO    MainThread:1603956 [wandb_setup.py:_flush():68] Loading settings from environment variables
2024-12-06 17:03:15,652 INFO    MainThread:1603956 [wandb_init.py:_log_setup():528] Logging user logs to /raid/students/mary/mlops-exercises/ME6/model_dev/wandb/run-20241206_170315-cqdgcp16/logs/debug.log
2024-12-06 17:03:15,652 INFO    MainThread:1603956 [wandb_init.py:_log_setup():529] Logging internal logs to /raid/students/mary/mlops-exercises/ME6/model_dev/wandb/run-20241206_170315-cqdgcp16/logs/debug-internal.log
2024-12-06 17:03:15,652 INFO    MainThread:1603956 [wandb_init.py:init():639] calling init triggers
2024-12-06 17:03:15,652 INFO    MainThread:1603956 [wandb_init.py:init():645] wandb.init called with sweep_config: {}
config: {}
2024-12-06 17:03:15,652 INFO    MainThread:1603956 [wandb_init.py:init():688] starting backend
2024-12-06 17:03:15,653 INFO    MainThread:1603956 [wandb_init.py:init():692] sending inform_init request
2024-12-06 17:03:15,654 INFO    MainThread:1603956 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-12-06 17:03:15,654 INFO    MainThread:1603956 [wandb_init.py:init():705] backend started and connected
2024-12-06 17:03:15,655 INFO    MainThread:1603956 [wandb_run.py:_label_probe_notebook():1327] probe notebook
2024-12-06 17:03:15,656 INFO    MainThread:1603956 [wandb_run.py:_label_probe_notebook():1337] Unable to probe notebook: Expecting value: line 1 column 1 (char 0)
2024-12-06 17:03:15,656 INFO    MainThread:1603956 [wandb_init.py:init():798] updated telemetry
2024-12-06 17:03:15,656 INFO    MainThread:1603956 [wandb_init.py:init():830] communicating run to backend with 120.0 second timeout
2024-12-06 17:03:58,916 WARNING MainThread:1603956 [wandb_init.py:init():1309] interrupted
Traceback (most recent call last):
  File "/data/students/mary/anaconda3/envs/AI231_ME6/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1305, in init
    return wi.init()
           ^^^^^^^^^
  File "/data/students/mary/anaconda3/envs/AI231_ME6/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 833, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/data/students/mary/anaconda3/envs/AI231_ME6/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 279, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/students/mary/anaconda3/envs/AI231_ME6/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/students/mary/anaconda3/envs/AI231_ME6/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 122, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/students/mary/anaconda3/envs/AI231_ME6/lib/python3.11/threading.py", line 629, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/students/mary/anaconda3/envs/AI231_ME6/lib/python3.11/threading.py", line 331, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2024-12-06 17:08:04,433 INFO    MainThread:1603956 [wandb_setup.py:_flush():68] Current SDK version is 0.19.0
2024-12-06 17:08:04,433 INFO    MainThread:1603956 [wandb_setup.py:_flush():68] Configure stats pid to 1603956
2024-12-06 17:08:04,433 INFO    MainThread:1603956 [wandb_setup.py:_flush():68] Loading settings from /data/students/mary/.config/wandb/settings
2024-12-06 17:08:04,433 INFO    MainThread:1603956 [wandb_setup.py:_flush():68] Loading settings from /raid/students/mary/mlops-exercises/ME6/model_dev/wandb/settings
2024-12-06 17:08:04,433 INFO    MainThread:1603956 [wandb_setup.py:_flush():68] Loading settings from environment variables
2024-12-06 17:08:04,433 INFO    MainThread:1603956 [wandb_init.py:_log_setup():528] Logging user logs to /raid/students/mary/mlops-exercises/ME6/model_dev/wandb/run-20241206_170804-1ed7f9l5/logs/debug.log
2024-12-06 17:08:04,434 INFO    MainThread:1603956 [wandb_init.py:_log_setup():529] Logging internal logs to /raid/students/mary/mlops-exercises/ME6/model_dev/wandb/run-20241206_170804-1ed7f9l5/logs/debug-internal.log
2024-12-06 17:08:04,434 INFO    MainThread:1603956 [wandb_init.py:init():639] calling init triggers
2024-12-06 17:08:04,434 INFO    MainThread:1603956 [wandb_init.py:init():645] wandb.init called with sweep_config: {}
config: {}
2024-12-06 17:08:04,434 INFO    MainThread:1603956 [wandb_init.py:init():688] starting backend
2024-12-06 17:08:04,434 INFO    MainThread:1603956 [wandb_init.py:init():692] sending inform_init request
2024-12-06 17:08:04,435 INFO    MainThread:1603956 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-12-06 17:08:04,435 INFO    MainThread:1603956 [wandb_init.py:init():705] backend started and connected
2024-12-06 17:08:04,436 INFO    MainThread:1603956 [wandb_run.py:_label_probe_notebook():1327] probe notebook
2024-12-06 17:08:04,436 INFO    MainThread:1603956 [wandb_run.py:_label_probe_notebook():1337] Unable to probe notebook: Expecting value: line 1 column 1 (char 0)
2024-12-06 17:08:04,436 INFO    MainThread:1603956 [wandb_init.py:init():798] updated telemetry
2024-12-06 17:08:04,437 INFO    MainThread:1603956 [wandb_init.py:init():830] communicating run to backend with 120.0 second timeout
2024-12-06 17:08:04,992 WARNING MsgRouterThr:1603956 [router.py:message_loop():75] message_loop has been closed
2024-12-06 17:08:04,992 WARNING MsgRouterThr:1603956 [router.py:message_loop():75] message_loop has been closed
2024-12-06 17:08:04,993 WARNING MsgRouterThr:1603956 [router.py:message_loop():75] message_loop has been closed
2024-12-06 17:08:04,993 WARNING MsgRouterThr:1603956 [router.py:message_loop():75] message_loop has been closed
2024-12-06 17:10:04,455 ERROR   MainThread:1603956 [wandb_init.py:init():857] encountered error: Run initialization has timed out after 120.0 sec. Please try increasing the timeout with the `init_timeout` setting: `wandb.init(settings=wandb.Settings(init_timeout=120))`.
2024-12-06 17:10:04,455 ERROR   MainThread:1603956 [wandb_init.py:init():1315] error in wandb.init()
Traceback (most recent call last):
  File "/data/students/mary/anaconda3/envs/AI231_ME6/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1305, in init
    return wi.init()
           ^^^^^^^^^
  File "/data/students/mary/anaconda3/envs/AI231_ME6/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 863, in init
    raise error
wandb.errors.errors.CommError: Run initialization has timed out after 120.0 sec. Please try increasing the timeout with the `init_timeout` setting: `wandb.init(settings=wandb.Settings(init_timeout=120))`.
